# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib gpindexr, .registration = TRUE
NULL

# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_gpindexr_wrappers", use_symbols = TRUE, package_name = "gpindexr")

#' @usage NULL
#' @useDynLib gpindexr, .registration = TRUE
NULL

r_average <- function(data) .Call(wrap__r_average, data)

r_geo_mean <- function(data) .Call(wrap__r_geo_mean, data)

# nolint end
